Race-boat-app/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Race_boat_app.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class Team
    {
        /// <summary>
        /// 
        /// </summary>
        public string Id;

        /// <summary>
        /// 
        /// </summary>
        public string CaptainID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string PitID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Recruiting { get; set; }
    }
}

Race-boat-app/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Race_boat_app.Models;
using Microsoft.AspNetCore.Http;

namespace Race_boat_app.Controllers
{
    /// <summary>
    /// Controller manages user requests in regards to teams
    /// and gathers information from the API regarding teams.
    /// </summary>
    public class TeamController : Controller
    {

        static HttpClient client = new HttpClient();
        private static readonly string passPhrase = "l%HJb5N^O@fl0K02H9PsxlR9algJTzK7ARBjJsd3fPG0&GwkrU";

        /// <summary>
        /// Gathers all teams from the API and sends them to the Teams
        /// view to display a list of all teams registered with
        /// the API.
        /// </summary>
        /// <returns>
        /// Attempts to return the teams view displaying all teams
        /// registered with the API.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public async Task<IActionResult> All()
        {
            try
            {
                List<Team> teams = await GetTeamsAsync("https://localhost:44389/api/1.0/team");
                List<User> users = new List<User>();
                foreach (var user in teams)
                {
                    User usr = await GetUserAsync("https://localhost:44389/api/1.0/user/" + user.CaptainID);
                    usr = DecryptUser(usr);
                    users.Add(usr);
                }
                List<string> recruiting = new List<string>();
                foreach (var rec in teams)
                {
                    recruiting.Add(rec.Recruiting);
                }
                ViewData["recruiting"] = recruiting;
                ViewData["users"] = users;
                return View("Teams");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }

        /// <summary>
        /// This method handels a users request to join a team.
        /// </summary>
        /// <param name="join">
        /// This object contains the teams ID
        /// </param>
        /// <returns>
        /// Whether successful or not at joining the team the user
        /// is redirected to the teams view page.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public async Task<IActionResult> JoinTeam(Join join) {
            //var hold = Request.Form["Team"];
            //var id = Request.Form["ID"];
            try
            {
                if (HttpContext.Session.GetString("_Posistion") == "Pit" && HttpContext.Session.GetString("_Team") == "null")
                {
                    var url = "https://localhost:44389/api/1.0/team/" + join.TeamID;
                    Team team = await GetTeamAsync(url.ToString());
                    team.PitID = HttpContext.Session.GetString("_ID");
                    team.Recruiting = "false";
                    await UpdateTeamAsync(team);
                    HttpContext.Session.SetString("_Team", team.Id);
                    User user1 = await UpdateUser();
                    List<Team> teams = await GetTeamsAsync("https://localhost:44389/api/1.0/team");
                    List<User> users = new List<User>();
                    List<string> recruiting = new List<string>();
                    foreach (var user in teams)
                    {
                        User usr = await GetUserAsync("https://localhost:44389/api/1.0/user/" + user.CaptainID);
                        usr = DecryptUser(usr);
                        users.Add(usr);
                    }
                    foreach (var rec in teams)
                    {
                        recruiting.Add(rec.Recruiting);
                    }
                    ViewData["recruiting"] = recruiting;
                    ViewData["users"] = users;
                    return RedirectToAction("All");
                }
                return RedirectToAction("All");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }

        /// <summary>
        /// This method handels a users request to create a team.
        /// </summary>
        /// <returns>
        /// Whether successful or not at creating a team the user
        /// is redirected to the teams view page.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public async Task<IActionResult> CreateTeam()
        {
            try
            {
                if (HttpContext.Session.GetString("_Posistion") == "Captain" && HttpContext.Session.GetString("_Team") == "null")
                {
                    string captainID1 = HttpContext.Session.GetString("_ID");
                    Team temp = new Team()
                    {
                        CaptainID = captainID1,
                        PitID = "null",
                        Recruiting = "true"
                    };
                    var url = await CreateTeamAsync(temp);
                    Team team = await GetTeamAsync(url.ToString());
                    HttpContext.Session.SetString("_Team", team.Id);
                    User user1 = await UpdateUser();
                    List<Team> teams = await GetTeamsAsync("https://localhost:44389/api/1.0/team");
                    List<User> users = new List<User>();
                    foreach (var user in teams)
                    {
                        User usr = await GetUserAsync("https://localhost:44389/api/1.0/user/" + user.CaptainID);
                        usr = DecryptUser(usr);
                        users.Add(usr);
                    }
                    List<string> recruiting = new List<string>();
                    foreach (var rec in teams)
                    {
                        recruiting.Add(rec.Recruiting);
                    }
                    ViewData["recruiting"] = recruiting;
                    ViewData["users"] = users;
                    return RedirectToAction("All");
                }
                return RedirectToAction("All");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }

        /// <summary>
        /// This method handels creating a view for displaying a teams
        /// information.
        /// </summary>
        /// <param name="join">
        /// This object contains the teams ID
        /// </param>
        /// <returns>
        /// If successful it will gather the captains information and if 
        /// possible the boat and pit's information as well. This is given to
        /// the team view page to be displayed to the user.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public async Task<IActionResult> DisplayTeam(Join join)
        {
            try
            { 
                var url = "https://localhost:44389/api/1.0/team/" + join.TeamID;
                Team team = await GetTeamAsync(url.ToString());
                var url2 = "https://localhost:44389/api/1.0/user/" + team.CaptainID;
                User captain = await GetUserAsync(url2.ToString());
                captain = DecryptUser(captain);
                ViewData["Captain"] = captain;
                List<Boat> boats = await GetBoatsAsync("https://localhost:44389/api/1.0/boat");
                Boat boatSend = null;
                foreach (Boat boat in boats)
                {
                    if (boat.CaptainID == team.CaptainID)
                    {
                        boatSend = boat;
                        ViewData["Boat"] = boat;
                    }
                }
                string hasBoat = "true";
                ViewData["hasBoat"] = hasBoat;
                if (boatSend == null)
                {
                    hasBoat = "false";
                    ViewData["hasBoat"] = hasBoat;
                }
                string hasPit = "false";
                ViewData["hasPit"] = hasPit;
                if (team.PitID != "null")
                {
                    var url3 = "https://localhost:44389/api/1.0/user/" + team.PitID;
                    User pit = await GetUserAsync(url3.ToString());
                    pit = DecryptUser(pit);
                    hasPit = "true";
                    ViewData["hasPit"] = hasPit;
                    ViewData["Pit"] = pit;
                }
                return View("TeamView");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }

Race-boat-app/Views/Team/TeamView.cshtml
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "TeamView";
    var captain = ViewData["Captain"] as User;
    var hasBoat = ViewData["hasBoat"] as string;
    var boat = new Boat();
    if (hasBoat == "true")
    {
        boat = ViewData["Boat"] as Boat;
    }
    var hasPit = ViewData["hasPit"] as string;
    var pit = new User();
    if (hasPit == "true")
    {
        pit = ViewData["Pit"] as User;
    }
}


<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h4>Captain @captain.FirstName</h4>
                            <p>Email: @captain.Email</p>
                            <p>Phone: @captain.MobilePhoneNumber</p>
                            <p>Points: @captain.Points</p>
                            @if (hasBoat == "true")
                            {
                                <h4>Boat</h4>
                                <p>Beam: @boat.Beam</p>
                                <p>Beam Measurement: @boat.BeamM</p>
                                <p>Type: @boat.Type</p>
                                <p>Drive System: @boat.DriveSystem</p>
                                <p>Hull Height: @boat.HullHeight</p>
                                <p>Hull Height Measurement: @boat.HullHeightM</p>
                                <p>Hull Material: @boat.HullMaterial</p>
                                <p>Length: @boat.Length</p>
                                <p>Length Measurement: @boat.LengthM</p>
                                <p>Motor Size: @boat.MotorSize</p>
                                <p>Propeller Size: @boat.PropellerSize</p>
                                <p>Radio: @boat.Radio</p>
                                <p>Scale: @boat.Scale</p>
                                <p>Scale Measurement: @boat.ScaleM</p>
                                <p>Speed: @boat.Speed</p>
                                <p>Speed Measurement: @boat.SpeedM</p>
                                <p>Speed Control: @boat.SpeedControl</p>
                                <p>Steering: @boat.Steering</p>
                                <p>Coluors: @boat.Coluors</p>
                                <p>Weight: @boat.Weight</p>
                                <p>Weight Measurement: @boat.WeightM</p>
                                
                            }
                            @if (hasPit == "true")
                            {
                                <h4>Pit @pit.FirstName</h4>
                                <p>Email: @pit.Email</p>
                                <p>Phone: @pit.MobilePhoneNumber</p>
                                <p>Points: @pit.Points</p>
                            }
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>
            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>
<!--/container-->

Race-boat-app/Views/Team/Teams.cshtml
@using Microsoft.AspNetCore.Http
@model Join
@{
    ViewData["Title"] = "Teams";
    var users = ViewData["users"] as List<User>;
    var recruiting = ViewData["recruiting"] as List<string>;
}
<div class="container">
    <div class="row">
        @*<div class="jumbotron jumbotron-fluid">
                <div class="container">
                    <h1 class="display-4">Fluid jumbotron</h1>
                    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
                </div>
            </div>*@
        <div class="heading-title text-center">
            <h3 class="text-uppercase">Team List</h3>
            @if (@Context.Session.GetString("_Posistion") == "Captain" && Context.Session.GetString("_LoggedIn") == "true" && Context.Session.GetString("_Team") == "null")
            {
                <form action="@Url.Action("CreateTeam", "Team")">
                    <button type="submit" class="btn btn-success btn-lg float-right">Create Team</button>
                </form>
            }
        </div>
        <!--var user in users-->
        @for (int i = 0; i < users.Count; i++)
        {



            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                        <div class="card">
                            <div class="card-horizontal">
                                <div class="img-square-wrapper">
                                    <img class="" style="max-width: 15vw" src="~/images/pp.svg" alt="Card image cap">
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-9">
                                            <h4>Captain @users[i].FirstName</h4>
                                            <p><span class="subtitles">Email:</span> @users[i].Email</p>
                                            <p><span class="subtitles">Phone:</span> @users[i].MobilePhoneNumber</p>
                                            <p><span class="subtitles">Points:</span> @users[i].Points</p>
                                            @if (Context.Session.GetString("_LoggedIn") == "true" && Context.Session.GetString("_Team") == users[i].Team)
                                            {
                                                <p>Your Team</p>
                                            }
                                        </div>
                                        <div class="col-lg-3" style="padding: 20px 15px">
                                            @if (Context.Session.GetString("_LoggedIn") == "true" && Context.Session.GetString("_Team") == "null" && recruiting[i] == "true"
                                               && Context.Session.GetString("_Posistion") == "Pit")
                                            {

                                                <form action="@Url.Action("JoinTeam", "Team")">
                                                    <input value=@users[i].Team type="hidden" asp-for="TeamID" />
                                                    <input value=@users[i].Id type="hidden" asp-for="Joiner" />
                                                    <button type="submit" class="btn btn-success btn-sm float-left" style="width: 100%; font-size: 1.3rem">Join Team</button>
                                                </form>

                                            }
                                            <form action="@Url.Action("DisplayTeam", "Team")">
                                                <input value=@users[i].Team type="hidden" asp-for="TeamID" />
                                                <input value=@users[i].Id type="hidden" asp-for="Joiner" />
                                                <button type="submit" class="btn btn-success btn-sm float-left" style="width: 100%; font-size: 1.3rem">View Team</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @*<div class="card-footer">
                                    <small class="text-muted">Last updated 3 mins ago</small>
                                </div>*@
                        </div>
                    </div>
                </div>
            </div>







            @*<div class="col-md-3 col-sm-3">
                    <div class="team-member">
                        <div class="team-img">
                            <img src="https://image.freepik.com/free-photo/man-standing-with-a-black-t-shirt_1187-1045.jpg" alt="team member" class="img-responsive">
                        </div>
                        <div class="team-hover" style=" word-break: break-word; margin-bottom: 3em; text-align: center;">

                            <h4>Captain @users[i].FirstName</h4>
                            <p>Email: @users[i].Email</p>
                            <p>Phone: @users[i].MobilePhoneNumber</p>
                            <p>Points: @users[i].Points</p>
                            @if (Context.Session.GetString("_LoggedIn") == "true" && Context.Session.GetString("_Team") == users[i].Team)
                            {
                                <p>Your Team</p>
                            }
                        </div>
                        <div class="s-link">
                            @if (Context.Session.GetString("_LoggedIn") == "true" && Context.Session.GetString("_Team") == "null" && recruiting[i] == "true"
                           && Context.Session.GetString("_Posistion") == "Pit")
                            {

                                <form action="@Url.Action("JoinTeam", "Team")">
                                    <input value=@users[i].Team type="hidden" asp-for="TeamID" />
                                    <input value=@users[i].Id type="hidden" asp-for="Joiner" />
                                    <button type="submit" class="btn btn-success btn-sm float-left">Join Team</button>
                                </form>

                            }
                            <form action="@Url.Action("DisplayTeam", "Team")">
                                <input value=@users[i].Team type="hidden" asp-for="TeamID" />
                                <input value=@users[i].Id type="hidden" asp-for="Joiner" />
                                <button type="submit" class="btn btn-success btn-sm float-left">View Team</button>
                            </form>

                        </div>
                    </div>
                </div>*@
            @*<div class="team-title">
                    <h5>Martin Smith</h5>
                    <span>founder &amp; ceo</span>
                </div>*@

        }
    </div>
</div>