Race-boat-app/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Race_boat_app.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class Event
    {
        /// <summary>
        /// 
        /// </summary>
        public string Id;

        /// <summary>
        /// 
        /// </summary>
        public string VideoURL { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string EventFileID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Date { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Location { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string TimeStart { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string TimeEnd { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    }
}

Race-boat-app/Models/EventReg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Race_boat_app.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class EventReg
    {
        /// <summary>
        /// 
        /// </summary>
        public string Id;

        /// <summary>
        /// 
        /// </summary>
        public string EventID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string TeamID { get; set; }
    }
}

Race-boat-app/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Race_boat_app.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Race_boat_app.Controllers
{
    /// <summary>
    /// This controller handels communicating user requests with API responses
    /// in regards to the Events and Registering intrests in competing in an
    /// Event.
    /// </summary>
    public class EventController : Controller
    {
        static HttpClient client = new HttpClient();

        /// <summary>
        /// Gets all events the API has to be displayed on the websites calander. 
        /// </summary>
        /// <returns>
        /// Returns the view events which displays all the events currently taking place.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public async Task<IActionResult> All()
        {
            try
            {
                List<EventReg> eventRegs = await GetEventRegsAsync("https://localhost:44389/api/1.0/eventReg");
                ViewData["eventRegs"] = eventRegs;
                return View("Events");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }
        /// <summary>
        /// Handels the Admins request to register an event with the API. 
        /// </summary>
        /// <returns>
        /// Returns the view where the admin can register the event with the API.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public IActionResult RegisterEvent()
        {
            return View("EventRegister");
        }


        /*[HttpPost]
        public async Task<IActionResult> ViewEvent(String id)
        {
            try
            {
                EventIn event1 = await GetEventAsync("https://localhost:44389/api/1.0/event/" + id);
                return RedirectToAction("EventRegister", event1);
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }*/

        /// <summary>
        /// Handels registering a teams intrest in competing in an Event. 
        /// </summary>
        /// <param name="download">
        /// Contains the TeamID and EventID that is required to register for the event.
        /// </param>
        /// <returns>
        /// If successful it will redirect the user to the All action 
        /// which returns the event calendar
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> RegisterTeam(Download download)
        {
            try
            {
                List<EventReg> eventRegs = await GetEventRegsAsync("https://localhost:44389/api/1.0/eventReg");
                ViewData["eventRegs"] = eventRegs;
                foreach (var reg in eventRegs)
                {
                    if (reg.EventID == download.Id && reg.TeamID == download.TeamId)
                    {
                        return RedirectToAction("All");
                        //return View("Events");
                    }
                }
                EventReg tempReg = new EventReg()
                {
                    EventID = download.Id,
                    TeamID = download.TeamId
                };
                var url = await CreateEventRegAsync(tempReg);
                //RedirectToAction("All");
                return RedirectToAction("All");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }

        /*public async Task<IActionResult> GetDownload(Download download) {
            string hold = download.Id;
            //await Download(hold);
            return View("Events");
        }*/

        /// <summary>
        /// This function is the first part of two that allows for the creation
        /// of an Event by the Admin
        /// </summary>
        /// <param name="events"></param>
        /// <returns>
        /// Returns the view update which will handle file uploading.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public ActionResult EventRegister(EventIn events)
        {//This must be an async task 
            try
            {
                HttpContext.Session.SetString("_VideoURL", events.VideoURL);
                HttpContext.Session.SetString("_EventName", events.Name);
                HttpContext.Session.SetString("_Date", events.Date);
                HttpContext.Session.SetString("_Location", events.Location);
                HttpContext.Session.SetString("_TimeStart", events.TimeStart);
                HttpContext.Session.SetString("_TimeEnd", events.TimeEnd);
                HttpContext.Session.SetString("_Description", events.Description);
                return View("upload");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }

        /// <summary>
        /// This function will handle gathering the information 
        /// needed to display an events information to an administrator 
        /// so that the event can be updated
        /// </summary>
        /// <param name="download">
        /// This object will contain the ID of the event that needs
        /// to be updated.
        /// </param>
        /// <returns>
        /// If successful it will return the event update view where an Admin 
        /// can edit an events information.
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        [HttpPost]
        public async Task<ActionResult> EditEvent(Download download)
        {
            try
            { 
                var url = "https://localhost:44389/api/1.0/event/" + download.Id;
                EventIn event1 = await GetEventAsync(url.ToString());
                HttpContext.Session.SetString("_VideoURL", event1.VideoURL);
                HttpContext.Session.SetString("_EventName", event1.Name);
                HttpContext.Session.SetString("_Date", event1.Date);
                HttpContext.Session.SetString("_Location", event1.Location);
                HttpContext.Session.SetString("_TimeStart", event1.TimeStart);
                HttpContext.Session.SetString("_TimeEnd", event1.TimeEnd);
                HttpContext.Session.SetString("_Description", event1.Description);
                HttpContext.Session.SetString("_EventID", event1.Id);
                return View("EventUpdate");
            }
            catch (Exception e)
            {
                string message = e.Message;
                string stackTrace = e.StackTrace;
                HttpContext.Session.SetString("_Error", "true");
                HttpContext.Session.SetString("_ErrorMessage", message);
                HttpContext.Session.SetString("_ErrorTrace", stackTrace);
                return View("Error");
            }
        }

        /// <summary>
        /// Handels updating an Event
        /// </summary>
        /// <param name="events">
        /// An object containing an events updated information.
        /// </param>
        /// <returns>
        /// If successful it will redirect the user to the All action 
        /// which returns the event calendar
        /// Should anything go wrong it will send the user to the Error page.
        /// </returns>
        public async Task<ActionResult> EventUpdater(EventIn events)
        {//This must be an async task 
            try
            { 
                List<EventReg> eventRegs = await GetEventRegsAsync("https://localhost:44389/api/1.0/eventReg");
                ViewData["eventRegs"] = eventRegs;
                EventIn event1 = await GetEventAsync("https://localhost:44389/api/1.0/event/" + HttpContext.Session.GetString("_EventID"));
                EventIn temp = new EventIn()
                {
                    Name = events.Name,
                    Location = events.Location,
                    Date = events.Date,
                    TimeStart = events.TimeStart,
                    TimeEnd = events.TimeEnd,
                    Description = events.Description,
                    VideoURL = events.VideoURL,
                    EventFile = event1.EventFile,
                    Id = event1.Id
                };
                var url = await UpdateEventAsync(temp);
                HttpContext.Session.SetString("_VideoURL", "Empty");
                HttpContext.Session.SetString("_EventName", "Empty");

Race-boat-app/Views/Event/EventRegister.cshtml
@model EventIn
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Register";
    var maxDate = DateTime.Today.Year;
    var maxMonth = DateTime.Today.Month;
    var maxDay = DateTime.Today.Day + 2;
    var maxMonthS = "";
    var maxDayS = "";
    if (maxMonth < 10)
    {
        maxMonthS = "0" + maxMonth.ToString();
    }
    else
    {
        maxMonthS = maxMonth.ToString();
    }
    if (maxDay < 10)
    {
        maxDayS = "0" + maxDay.ToString();
    }
    if (DateTime.Today.Day == 30 || DateTime.Today.Day == 31)
    {
        maxDayS = "02";
        maxMonth = DateTime.Today.Month + 1;
        maxMonthS = maxMonth.ToString();
    }
    else
    {
        maxDayS = maxDay.ToString();
    }
}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">Event Register</h3>
                        </div>
                        <div class="card-body">
                            @if (Context.Session.GetString("_Admin") == "true")
                            {

                                <form class="form" method="post" action="@Url.Action("EventRegister", "Event")">
                                    VideoURL: <input class="form-control form-control-lg rounded-0" value="Null" asp-for="VideoURL" required />
                                    Name: <input class="form-control form-control-lg rounded-0" asp-for="Name" required />
                                    Date: <input class="form-control form-control-lg rounded-0" type="date" max="2022-01-01" min="@maxDate-@maxMonthS-@maxDayS" asp-for="Date" required />
                                    Location: <input class="form-control form-control-lg rounded-0" asp-for="Location" required />
                                    Time Start: <input id="startTime" type="time" class="form-control form-control-lg rounded-0" asp-for="TimeStart" required />
                                    Time End: <input id="endTime" type="time" class="form-control form-control-lg rounded-0" asp-for="TimeEnd" required />
                                    Description: <input class="form-control form-control-lg rounded-0" asp-for="Description" required />
                                    <button type="submit" class="btn btn-success btn-lg float-right" id="submitAll">Submit</button>
                                </form>

                            }
                            @if (Context.Session.GetString("_Admin") == "false")
                            {
                                <p>You Don't have permision to access this</p>
                            }
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>
            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
    <script>
        var startTime = document.getElementById("startTime");
        var endTime = document.getElementById("endTime");

        startTime.addEventListener("input", function () {
            endTime.min = startTime.value;
        }, false);
        endTime.addEventListener("input", function () {
            startTime.max = endTime.value;
        }, false);
    </script>
</div>

Race-boat-app/Views/Event/EventRegs.cshtml
@using Microsoft.AspNetCore.Http
    @{
        ViewData["Title"] = "EventRegs";
        var users = ViewData.Model;
    }

    @*<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <script>
            $(document).ready(function () {
                $('#submitAll').on('click', function () {
                    var data = $("form").serialize();
                    console.log(data);
                    // Make Ajax request with the contentType = false, and procesDate = false
                    var ajaxRequest = $.ajax({
                        type: "POST",
                        url: "Index2",
                        contentType: false,
                        processData: false,
                        data: data
                    });
                    ajaxRequest.done(function (xhr, textStatus) {
                        // Do other operation
                    });
                });
            });
        </script>*@




    @*<table>

            @foreach (var user in users)
            {
                <tr>
                    <td>@user.FirstName</td>

                </tr>
            }
        </table>*@


    <div class="container">
        <div class="row">
            @foreach (var user in users)
            {
                <div class="col-sm-4">
                    <div class="card user-card">
                        <img class="card-img-top" src="~/images/profile.jpg" alt="Card image cap">
                        <div class="card-body user-card-body text-center">
                            @if (Context.Session.GetString("_Admin") == "true")
                            {
                                    <p class="card-text">
                                        <span>ID: @user.Id</span><br />
                                        <span>Team: @user.TeamID</span><br />
                                        <span>Event: @user.EventID</span><br />
                                        
                                    </p>
                            }
                        @if (Context.Session.GetString("_Admin") == "false")
                        {
                            
                                <p>You Don't have permision to access this</p>
                            
                        }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

Race-boat-app/Views/Event/EventUpdate.cshtml
@model EventIn
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Register";
    var maxDate = DateTime.Today.Year;
    var maxMonth = DateTime.Today.Month;
    var maxDay = DateTime.Today.Day + 2;
    var maxMonthS = "";
    var maxDayS = "";
    if (maxMonth < 10)
    {
        maxMonthS = "0" + maxMonth.ToString();
    }
    else
    {
        maxMonthS = maxMonth.ToString();
    }
    if (maxDay < 10)
    {
        maxDayS = "0" + maxDay.ToString();
    }
    if (DateTime.Today.Day == 30 || DateTime.Today.Day == 31)
    {
        maxDayS = "02";
        maxMonth = DateTime.Today.Month + 1;
        maxMonthS = maxMonth.ToString();
    }
    else
    {
        maxDayS = maxDay.ToString();
    }
}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">Update Event</h3>
                        </div>
                        <div class="card-body">
                            @if (Context.Session.GetString("_Admin") == "true")
                            {

                                <form class="form" method="post" action="@Url.Action("EventUpdater", "Event")">
                                    ID: <input class="form-control form-control-lg rounded-0" disabled value=@Context.Session.GetString("_EventID") asp-for="Id" required />
                                    VideoURL: <input class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_VideoURL") asp-for="VideoURL" required />
                                    Name: <input class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_EventName") asp-for="Name" required />
                                    Date: <input class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_Date") type="date" max="2022-01-01" min="@maxDate-@maxMonthS-@maxDayS" asp-for="Date" required />
                                    Location: <input class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_Location") asp-for="Location" required />
                                    Time Start: <input id="startTime" max=@Context.Session.GetString("_TimeEnd") type="time" class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_TimeStart") asp-for="TimeStart" required />
                                    Time End: <input id="endTime" type="time" min=@Context.Session.GetString("_TimeStart") class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_TimeEnd") asp-for="TimeEnd" required />
                                    Description: <input class="form-control form-control-lg rounded-0" value=@Context.Session.GetString("_Description") asp-for="Description" required />
                                    <button type="submit" class="btn btn-success btn-lg float-right" id="submitAll">Submit</button>
                                </form>

                               <!-- <form method="post" action="@Url.Action("UploadNewFile", "Event")">

                                    <input type="submit" class="btn btn-success btn-sm float-left" value="Upload New File Only" />

                                </form> -->

                            }
                            @if (Context.Session.GetString("_Admin") == "false")
                            {
                                <p>You Don't have permision to access this</p>
                            }
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>
            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
    <script>
        var startTime = document.getElementById("startTime");
        var endTime = document.getElementById("endTime");

        startTime.addEventListener("input", function () {
            endTime.min = startTime.value;
        }, false);

        endTime.addEventListener("input", function () {
            startTime.max = endTime.value;
        }, false);
    </script>
</div>

Race-boat-app/Views/Event/EventView.cshtml
@{
    ViewData["Title"] = "EventView";
    var event1 = ViewData.Model;
}

<h1>EventView</h1>


@event1.id

Race-boat-app/Views/Event/Events.cshtml
@model Download
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Events";
    var eventRegs = ViewData["eventRegs"] as List<EventReg>;

}





<ul  hidden id="events">
    @foreach (var element in eventRegs)
    {
        <li data-store=@element.EventID></li>
    }
</ul>
<ul hidden id="teams">
    @foreach (var element in eventRegs)
    {
        <li data-store=@element.TeamID></li>
    }
</ul>
<ul hidden id="user">
    <li data-store=@Context.Session.GetString("_Team")></li>
</ul>


<div id='calendar'></div>


@*<div id="calendarModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                    <h4 id="modalTitle" class="modal-title"></h4>
                </div>
                <div id="modalBody" class="modal-body"> </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>*@

<div class="modal" id="calendarModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle"></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div id="modalBody" class="modal-body">
                <div class="col-md-12">
                    <span class="col-md-4">Location</span>:
                    <span class="col-md-7" id="eventLoc"></span>
                </div>
                <div class="col-md-12">
                    <span class="col-md-4">Date</span>:
                    <span class="col-md-7" id="eventDate"></span>
                </div>
                <div class="col-md-12">
                    <span class="col-md-4">Start Time</span>:
                    <span class="col-md-7" id="eventSTime"></span>
                </div>
                <div class="col-md-12">
                    <span class="col-md-4">End Time</span>:
                    <span class="col-md-7" id="eventETime"></span>
                </div>
                <div class="col-md-12">
                    <span class="col-md-4">Desc</span>:
                    <span class="col-md-7" id="eventDesc"></span>
                </div>
                <div class="col-md-12">

                    <form action="@Url.Action("Download", "Event")">
                        <input id="eventSID1" value="" type="hidden" asp-for="Id" />
                        <button type="submit" class="btn btn-success btn-sm float-left">Download Flyer</button>
                    </form>

                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">

                @if (Context.Session.GetString("_LoggedIn") == "true" && Context.Session.GetString("_Team") != "null")
                {
                    <form method="post" action="@Url.Action("RegisterTeam", "Event")">

                        <input id="eventSID2" value="" type="hidden" asp-for="Id" />
                        <input value=@Context.Session.GetString("_Team") type="hidden" asp-for="TeamId" />
                        <input type="submit" class="btn btn-success btn-sm float-left" id="RegButton" name="" value="Register" />

                    </form>
                }
                @if (Context.Session.GetString("_Admin") == "true")
                {
                    <form method="post" action="@Url.Action("EditEvent", "Event")">

                        <input id="eventSID3" value="" type="hidden" asp-for="Id" />
                        <input type="submit" class="btn btn-success btn-sm float-left" id="EditButton" name="" value="Edit" />

                    </form>
                }
                
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<script>
        function RegisterEvent()
            {
                //var dataRow = {
                //    'id': EventID,
                //    'NewEventStart': EventStart,
                //    'NewEventEnd': EventEnd
                //}
                @*console.log(EventID);
        $.ajax({
            type: 'POST',
            url: "@Url.Action("ViewEvent","Event")",
            dataType: "json",
            contentType: "application/json",
            data: JSON.stringify({ id: EventID }),
            success: function (data) {
                console.log(data)

            }

        });*@

                //$.ajax({
                //    type: "POST",
                //    url: url,
                //    data: EventID,
                //    cache: false,
                //    dataType: 'json',
                //    success: function (result) {
                //        if (result == '200') {
                //            alert('successfuly inserted');
                //        }
                //        else {
                //            alert('some error occured');
                //        }
                //    }
                //});

                //$.ajax({
                //    url: '/Event/ViewEvent/' + EventID,
                //}).done(function () {

                //});
                var eId = sessionStorage.getItem('e_id');
                console.log("ssid", eId);
                $.ajax({
                type: "POST",
                url: 'viewEvent/'+eId,
                //url: '@Url.Action("ViewEvent")',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                alert(data);
                },
                failure: function (errMsg) {
                alert(errMsg);
                }
                }).done(function () {

                });
                }
</script>